// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/supplier"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// SupplierCreate is the builder for creating a Supplier entity.
type SupplierCreate struct {
	config
	mutation *SupplierMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SupplierCreate) SetCreatedAt(v time.Time) *SupplierCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SupplierCreate) SetNillableCreatedAt(v *time.Time) *SupplierCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SupplierCreate) SetUpdatedAt(v time.Time) *SupplierCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SupplierCreate) SetNillableUpdatedAt(v *time.Time) *SupplierCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SupplierCreate) SetDeletedAt(v time.Time) *SupplierCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SupplierCreate) SetNillableDeletedAt(v *time.Time) *SupplierCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *SupplierCreate) SetCode(v string) *SupplierCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SupplierCreate) SetName(v string) *SupplierCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SupplierCreate) SetStatus(v string) *SupplierCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SupplierCreate) SetNillableStatus(v *string) *SupplierCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *SupplierCreate) SetNotes(v string) *SupplierCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *SupplierCreate) SetNillableNotes(v *string) *SupplierCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetAllowedAccountKinds sets the "allowed_account_kinds" field.
func (_c *SupplierCreate) SetAllowedAccountKinds(v []domain.SupplierAccountKind) *SupplierCreate {
	_c.mutation.SetAllowedAccountKinds(v)
	return _c
}

// SetReviewRequired sets the "review_required" field.
func (_c *SupplierCreate) SetReviewRequired(v bool) *SupplierCreate {
	_c.mutation.SetReviewRequired(v)
	return _c
}

// SetNillableReviewRequired sets the "review_required" field if the given value is not nil.
func (_c *SupplierCreate) SetNillableReviewRequired(v *bool) *SupplierCreate {
	if v != nil {
		_c.SetReviewRequired(*v)
	}
	return _c
}

// SetAutoApproveGroups sets the "auto_approve_groups" field.
func (_c *SupplierCreate) SetAutoApproveGroups(v map[string][]int64) *SupplierCreate {
	_c.mutation.SetAutoApproveGroups(v)
	return _c
}

// SetTokenSelector sets the "token_selector" field.
func (_c *SupplierCreate) SetTokenSelector(v string) *SupplierCreate {
	_c.mutation.SetTokenSelector(v)
	return _c
}

// SetNillableTokenSelector sets the "token_selector" field if the given value is not nil.
func (_c *SupplierCreate) SetNillableTokenSelector(v *string) *SupplierCreate {
	if v != nil {
		_c.SetTokenSelector(*v)
	}
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *SupplierCreate) SetTokenHash(v string) *SupplierCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_c *SupplierCreate) SetNillableTokenHash(v *string) *SupplierCreate {
	if v != nil {
		_c.SetTokenHash(*v)
	}
	return _c
}

// SetTokenPrefix sets the "token_prefix" field.
func (_c *SupplierCreate) SetTokenPrefix(v string) *SupplierCreate {
	_c.mutation.SetTokenPrefix(v)
	return _c
}

// SetNillableTokenPrefix sets the "token_prefix" field if the given value is not nil.
func (_c *SupplierCreate) SetNillableTokenPrefix(v *string) *SupplierCreate {
	if v != nil {
		_c.SetTokenPrefix(*v)
	}
	return _c
}

// SetTokenCreatedAt sets the "token_created_at" field.
func (_c *SupplierCreate) SetTokenCreatedAt(v time.Time) *SupplierCreate {
	_c.mutation.SetTokenCreatedAt(v)
	return _c
}

// SetNillableTokenCreatedAt sets the "token_created_at" field if the given value is not nil.
func (_c *SupplierCreate) SetNillableTokenCreatedAt(v *time.Time) *SupplierCreate {
	if v != nil {
		_c.SetTokenCreatedAt(*v)
	}
	return _c
}

// SetTokenLastUsedAt sets the "token_last_used_at" field.
func (_c *SupplierCreate) SetTokenLastUsedAt(v time.Time) *SupplierCreate {
	_c.mutation.SetTokenLastUsedAt(v)
	return _c
}

// SetNillableTokenLastUsedAt sets the "token_last_used_at" field if the given value is not nil.
func (_c *SupplierCreate) SetNillableTokenLastUsedAt(v *time.Time) *SupplierCreate {
	if v != nil {
		_c.SetTokenLastUsedAt(*v)
	}
	return _c
}

// AddMemberIDs adds the "members" edge to the User entity by IDs.
func (_c *SupplierCreate) AddMemberIDs(ids ...int64) *SupplierCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the User entity.
func (_c *SupplierCreate) AddMembers(v ...*User) *SupplierCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *SupplierCreate) AddAccountIDs(ids ...int64) *SupplierCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *SupplierCreate) AddAccounts(v ...*Account) *SupplierCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// Mutation returns the SupplierMutation object of the builder.
func (_c *SupplierCreate) Mutation() *SupplierMutation {
	return _c.mutation
}

// Save creates the Supplier in the database.
func (_c *SupplierCreate) Save(ctx context.Context) (*Supplier, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SupplierCreate) SaveX(ctx context.Context) *Supplier {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupplierCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupplierCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SupplierCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if supplier.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized supplier.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := supplier.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if supplier.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized supplier.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := supplier.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := supplier.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AllowedAccountKinds(); !ok {
		if supplier.DefaultAllowedAccountKinds == nil {
			return fmt.Errorf("ent: uninitialized supplier.DefaultAllowedAccountKinds (forgotten import ent/runtime?)")
		}
		v := supplier.DefaultAllowedAccountKinds()
		_c.mutation.SetAllowedAccountKinds(v)
	}
	if _, ok := _c.mutation.ReviewRequired(); !ok {
		v := supplier.DefaultReviewRequired
		_c.mutation.SetReviewRequired(v)
	}
	if _, ok := _c.mutation.AutoApproveGroups(); !ok {
		if supplier.DefaultAutoApproveGroups == nil {
			return fmt.Errorf("ent: uninitialized supplier.DefaultAutoApproveGroups (forgotten import ent/runtime?)")
		}
		v := supplier.DefaultAutoApproveGroups()
		_c.mutation.SetAutoApproveGroups(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SupplierCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Supplier.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Supplier.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Supplier.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := supplier.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Supplier.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Supplier.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := supplier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Supplier.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Supplier.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := supplier.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Supplier.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AllowedAccountKinds(); !ok {
		return &ValidationError{Name: "allowed_account_kinds", err: errors.New(`ent: missing required field "Supplier.allowed_account_kinds"`)}
	}
	if _, ok := _c.mutation.ReviewRequired(); !ok {
		return &ValidationError{Name: "review_required", err: errors.New(`ent: missing required field "Supplier.review_required"`)}
	}
	if _, ok := _c.mutation.AutoApproveGroups(); !ok {
		return &ValidationError{Name: "auto_approve_groups", err: errors.New(`ent: missing required field "Supplier.auto_approve_groups"`)}
	}
	if v, ok := _c.mutation.TokenSelector(); ok {
		if err := supplier.TokenSelectorValidator(v); err != nil {
			return &ValidationError{Name: "token_selector", err: fmt.Errorf(`ent: validator failed for field "Supplier.token_selector": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := supplier.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "Supplier.token_hash": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TokenPrefix(); ok {
		if err := supplier.TokenPrefixValidator(v); err != nil {
			return &ValidationError{Name: "token_prefix", err: fmt.Errorf(`ent: validator failed for field "Supplier.token_prefix": %w`, err)}
		}
	}
	return nil
}

func (_c *SupplierCreate) sqlSave(ctx context.Context) (*Supplier, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SupplierCreate) createSpec() (*Supplier, *sqlgraph.CreateSpec) {
	var (
		_node = &Supplier{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(supplier.Table, sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(supplier.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(supplier.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(supplier.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(supplier.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(supplier.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(supplier.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(supplier.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.AllowedAccountKinds(); ok {
		_spec.SetField(supplier.FieldAllowedAccountKinds, field.TypeJSON, value)
		_node.AllowedAccountKinds = value
	}
	if value, ok := _c.mutation.ReviewRequired(); ok {
		_spec.SetField(supplier.FieldReviewRequired, field.TypeBool, value)
		_node.ReviewRequired = value
	}
	if value, ok := _c.mutation.AutoApproveGroups(); ok {
		_spec.SetField(supplier.FieldAutoApproveGroups, field.TypeJSON, value)
		_node.AutoApproveGroups = value
	}
	if value, ok := _c.mutation.TokenSelector(); ok {
		_spec.SetField(supplier.FieldTokenSelector, field.TypeString, value)
		_node.TokenSelector = &value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(supplier.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = &value
	}
	if value, ok := _c.mutation.TokenPrefix(); ok {
		_spec.SetField(supplier.FieldTokenPrefix, field.TypeString, value)
		_node.TokenPrefix = &value
	}
	if value, ok := _c.mutation.TokenCreatedAt(); ok {
		_spec.SetField(supplier.FieldTokenCreatedAt, field.TypeTime, value)
		_node.TokenCreatedAt = &value
	}
	if value, ok := _c.mutation.TokenLastUsedAt(); ok {
		_spec.SetField(supplier.FieldTokenLastUsedAt, field.TypeTime, value)
		_node.TokenLastUsedAt = &value
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.MembersTable,
			Columns: []string{supplier.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.AccountsTable,
			Columns: []string{supplier.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Supplier.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupplierUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SupplierCreate) OnConflict(opts ...sql.ConflictOption) *SupplierUpsertOne {
	_c.conflict = opts
	return &SupplierUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Supplier.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupplierCreate) OnConflictColumns(columns ...string) *SupplierUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupplierUpsertOne{
		create: _c,
	}
}

type (
	// SupplierUpsertOne is the builder for "upsert"-ing
	//  one Supplier node.
	SupplierUpsertOne struct {
		create *SupplierCreate
	}

	// SupplierUpsert is the "OnConflict" setter.
	SupplierUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SupplierUpsert) SetUpdatedAt(v time.Time) *SupplierUpsert {
	u.Set(supplier.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupplierUpsert) UpdateUpdatedAt() *SupplierUpsert {
	u.SetExcluded(supplier.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SupplierUpsert) SetDeletedAt(v time.Time) *SupplierUpsert {
	u.Set(supplier.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SupplierUpsert) UpdateDeletedAt() *SupplierUpsert {
	u.SetExcluded(supplier.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SupplierUpsert) ClearDeletedAt() *SupplierUpsert {
	u.SetNull(supplier.FieldDeletedAt)
	return u
}

// SetCode sets the "code" field.
func (u *SupplierUpsert) SetCode(v string) *SupplierUpsert {
	u.Set(supplier.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *SupplierUpsert) UpdateCode() *SupplierUpsert {
	u.SetExcluded(supplier.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *SupplierUpsert) SetName(v string) *SupplierUpsert {
	u.Set(supplier.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SupplierUpsert) UpdateName() *SupplierUpsert {
	u.SetExcluded(supplier.FieldName)
	return u
}

// SetStatus sets the "status" field.
func (u *SupplierUpsert) SetStatus(v string) *SupplierUpsert {
	u.Set(supplier.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupplierUpsert) UpdateStatus() *SupplierUpsert {
	u.SetExcluded(supplier.FieldStatus)
	return u
}

// SetNotes sets the "notes" field.
func (u *SupplierUpsert) SetNotes(v string) *SupplierUpsert {
	u.Set(supplier.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SupplierUpsert) UpdateNotes() *SupplierUpsert {
	u.SetExcluded(supplier.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *SupplierUpsert) ClearNotes() *SupplierUpsert {
	u.SetNull(supplier.FieldNotes)
	return u
}

// SetAllowedAccountKinds sets the "allowed_account_kinds" field.
func (u *SupplierUpsert) SetAllowedAccountKinds(v []domain.SupplierAccountKind) *SupplierUpsert {
	u.Set(supplier.FieldAllowedAccountKinds, v)
	return u
}

// UpdateAllowedAccountKinds sets the "allowed_account_kinds" field to the value that was provided on create.
func (u *SupplierUpsert) UpdateAllowedAccountKinds() *SupplierUpsert {
	u.SetExcluded(supplier.FieldAllowedAccountKinds)
	return u
}

// SetReviewRequired sets the "review_required" field.
func (u *SupplierUpsert) SetReviewRequired(v bool) *SupplierUpsert {
	u.Set(supplier.FieldReviewRequired, v)
	return u
}

// UpdateReviewRequired sets the "review_required" field to the value that was provided on create.
func (u *SupplierUpsert) UpdateReviewRequired() *SupplierUpsert {
	u.SetExcluded(supplier.FieldReviewRequired)
	return u
}

// SetAutoApproveGroups sets the "auto_approve_groups" field.
func (u *SupplierUpsert) SetAutoApproveGroups(v map[string][]int64) *SupplierUpsert {
	u.Set(supplier.FieldAutoApproveGroups, v)
	return u
}

// UpdateAutoApproveGroups sets the "auto_approve_groups" field to the value that was provided on create.
func (u *SupplierUpsert) UpdateAutoApproveGroups() *SupplierUpsert {
	u.SetExcluded(supplier.FieldAutoApproveGroups)
	return u
}

// SetTokenSelector sets the "token_selector" field.
func (u *SupplierUpsert) SetTokenSelector(v string) *SupplierUpsert {
	u.Set(supplier.FieldTokenSelector, v)
	return u
}

// UpdateTokenSelector sets the "token_selector" field to the value that was provided on create.
func (u *SupplierUpsert) UpdateTokenSelector() *SupplierUpsert {
	u.SetExcluded(supplier.FieldTokenSelector)
	return u
}

// ClearTokenSelector clears the value of the "token_selector" field.
func (u *SupplierUpsert) ClearTokenSelector() *SupplierUpsert {
	u.SetNull(supplier.FieldTokenSelector)
	return u
}

// SetTokenHash sets the "token_hash" field.
func (u *SupplierUpsert) SetTokenHash(v string) *SupplierUpsert {
	u.Set(supplier.FieldTokenHash, v)
	return u
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *SupplierUpsert) UpdateTokenHash() *SupplierUpsert {
	u.SetExcluded(supplier.FieldTokenHash)
	return u
}

// ClearTokenHash clears the value of the "token_hash" field.
func (u *SupplierUpsert) ClearTokenHash() *SupplierUpsert {
	u.SetNull(supplier.FieldTokenHash)
	return u
}

// SetTokenPrefix sets the "token_prefix" field.
func (u *SupplierUpsert) SetTokenPrefix(v string) *SupplierUpsert {
	u.Set(supplier.FieldTokenPrefix, v)
	return u
}

// UpdateTokenPrefix sets the "token_prefix" field to the value that was provided on create.
func (u *SupplierUpsert) UpdateTokenPrefix() *SupplierUpsert {
	u.SetExcluded(supplier.FieldTokenPrefix)
	return u
}

// ClearTokenPrefix clears the value of the "token_prefix" field.
func (u *SupplierUpsert) ClearTokenPrefix() *SupplierUpsert {
	u.SetNull(supplier.FieldTokenPrefix)
	return u
}

// SetTokenCreatedAt sets the "token_created_at" field.
func (u *SupplierUpsert) SetTokenCreatedAt(v time.Time) *SupplierUpsert {
	u.Set(supplier.FieldTokenCreatedAt, v)
	return u
}

// UpdateTokenCreatedAt sets the "token_created_at" field to the value that was provided on create.
func (u *SupplierUpsert) UpdateTokenCreatedAt() *SupplierUpsert {
	u.SetExcluded(supplier.FieldTokenCreatedAt)
	return u
}

// ClearTokenCreatedAt clears the value of the "token_created_at" field.
func (u *SupplierUpsert) ClearTokenCreatedAt() *SupplierUpsert {
	u.SetNull(supplier.FieldTokenCreatedAt)
	return u
}

// SetTokenLastUsedAt sets the "token_last_used_at" field.
func (u *SupplierUpsert) SetTokenLastUsedAt(v time.Time) *SupplierUpsert {
	u.Set(supplier.FieldTokenLastUsedAt, v)
	return u
}

// UpdateTokenLastUsedAt sets the "token_last_used_at" field to the value that was provided on create.
func (u *SupplierUpsert) UpdateTokenLastUsedAt() *SupplierUpsert {
	u.SetExcluded(supplier.FieldTokenLastUsedAt)
	return u
}

// ClearTokenLastUsedAt clears the value of the "token_last_used_at" field.
func (u *SupplierUpsert) ClearTokenLastUsedAt() *SupplierUpsert {
	u.SetNull(supplier.FieldTokenLastUsedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Supplier.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupplierUpsertOne) UpdateNewValues() *SupplierUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(supplier.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Supplier.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SupplierUpsertOne) Ignore() *SupplierUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupplierUpsertOne) DoNothing() *SupplierUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupplierCreate.OnConflict
// documentation for more info.
func (u *SupplierUpsertOne) Update(set func(*SupplierUpsert)) *SupplierUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupplierUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SupplierUpsertOne) SetUpdatedAt(v time.Time) *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupplierUpsertOne) UpdateUpdatedAt() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SupplierUpsertOne) SetDeletedAt(v time.Time) *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SupplierUpsertOne) UpdateDeletedAt() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SupplierUpsertOne) ClearDeletedAt() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCode sets the "code" field.
func (u *SupplierUpsertOne) SetCode(v string) *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *SupplierUpsertOne) UpdateCode() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *SupplierUpsertOne) SetName(v string) *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SupplierUpsertOne) UpdateName() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *SupplierUpsertOne) SetStatus(v string) *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupplierUpsertOne) UpdateStatus() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateStatus()
	})
}

// SetNotes sets the "notes" field.
func (u *SupplierUpsertOne) SetNotes(v string) *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SupplierUpsertOne) UpdateNotes() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *SupplierUpsertOne) ClearNotes() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.ClearNotes()
	})
}

// SetAllowedAccountKinds sets the "allowed_account_kinds" field.
func (u *SupplierUpsertOne) SetAllowedAccountKinds(v []domain.SupplierAccountKind) *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.SetAllowedAccountKinds(v)
	})
}

// UpdateAllowedAccountKinds sets the "allowed_account_kinds" field to the value that was provided on create.
func (u *SupplierUpsertOne) UpdateAllowedAccountKinds() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateAllowedAccountKinds()
	})
}

// SetReviewRequired sets the "review_required" field.
func (u *SupplierUpsertOne) SetReviewRequired(v bool) *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.SetReviewRequired(v)
	})
}

// UpdateReviewRequired sets the "review_required" field to the value that was provided on create.
func (u *SupplierUpsertOne) UpdateReviewRequired() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateReviewRequired()
	})
}

// SetAutoApproveGroups sets the "auto_approve_groups" field.
func (u *SupplierUpsertOne) SetAutoApproveGroups(v map[string][]int64) *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.SetAutoApproveGroups(v)
	})
}

// UpdateAutoApproveGroups sets the "auto_approve_groups" field to the value that was provided on create.
func (u *SupplierUpsertOne) UpdateAutoApproveGroups() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateAutoApproveGroups()
	})
}

// SetTokenSelector sets the "token_selector" field.
func (u *SupplierUpsertOne) SetTokenSelector(v string) *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.SetTokenSelector(v)
	})
}

// UpdateTokenSelector sets the "token_selector" field to the value that was provided on create.
func (u *SupplierUpsertOne) UpdateTokenSelector() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateTokenSelector()
	})
}

// ClearTokenSelector clears the value of the "token_selector" field.
func (u *SupplierUpsertOne) ClearTokenSelector() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.ClearTokenSelector()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *SupplierUpsertOne) SetTokenHash(v string) *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *SupplierUpsertOne) UpdateTokenHash() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateTokenHash()
	})
}

// ClearTokenHash clears the value of the "token_hash" field.
func (u *SupplierUpsertOne) ClearTokenHash() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.ClearTokenHash()
	})
}

// SetTokenPrefix sets the "token_prefix" field.
func (u *SupplierUpsertOne) SetTokenPrefix(v string) *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.SetTokenPrefix(v)
	})
}

// UpdateTokenPrefix sets the "token_prefix" field to the value that was provided on create.
func (u *SupplierUpsertOne) UpdateTokenPrefix() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateTokenPrefix()
	})
}

// ClearTokenPrefix clears the value of the "token_prefix" field.
func (u *SupplierUpsertOne) ClearTokenPrefix() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.ClearTokenPrefix()
	})
}

// SetTokenCreatedAt sets the "token_created_at" field.
func (u *SupplierUpsertOne) SetTokenCreatedAt(v time.Time) *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.SetTokenCreatedAt(v)
	})
}

// UpdateTokenCreatedAt sets the "token_created_at" field to the value that was provided on create.
func (u *SupplierUpsertOne) UpdateTokenCreatedAt() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateTokenCreatedAt()
	})
}

// ClearTokenCreatedAt clears the value of the "token_created_at" field.
func (u *SupplierUpsertOne) ClearTokenCreatedAt() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.ClearTokenCreatedAt()
	})
}

// SetTokenLastUsedAt sets the "token_last_used_at" field.
func (u *SupplierUpsertOne) SetTokenLastUsedAt(v time.Time) *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.SetTokenLastUsedAt(v)
	})
}

// UpdateTokenLastUsedAt sets the "token_last_used_at" field to the value that was provided on create.
func (u *SupplierUpsertOne) UpdateTokenLastUsedAt() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateTokenLastUsedAt()
	})
}

// ClearTokenLastUsedAt clears the value of the "token_last_used_at" field.
func (u *SupplierUpsertOne) ClearTokenLastUsedAt() *SupplierUpsertOne {
	return u.Update(func(s *SupplierUpsert) {
		s.ClearTokenLastUsedAt()
	})
}

// Exec executes the query.
func (u *SupplierUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupplierCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupplierUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SupplierUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SupplierUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SupplierCreateBulk is the builder for creating many Supplier entities in bulk.
type SupplierCreateBulk struct {
	config
	err      error
	builders []*SupplierCreate
	conflict []sql.ConflictOption
}

// Save creates the Supplier entities in the database.
func (_c *SupplierCreateBulk) Save(ctx context.Context) ([]*Supplier, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Supplier, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupplierMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SupplierCreateBulk) SaveX(ctx context.Context) []*Supplier {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupplierCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupplierCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Supplier.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupplierUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SupplierCreateBulk) OnConflict(opts ...sql.ConflictOption) *SupplierUpsertBulk {
	_c.conflict = opts
	return &SupplierUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Supplier.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupplierCreateBulk) OnConflictColumns(columns ...string) *SupplierUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupplierUpsertBulk{
		create: _c,
	}
}

// SupplierUpsertBulk is the builder for "upsert"-ing
// a bulk of Supplier nodes.
type SupplierUpsertBulk struct {
	create *SupplierCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Supplier.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupplierUpsertBulk) UpdateNewValues() *SupplierUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(supplier.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Supplier.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SupplierUpsertBulk) Ignore() *SupplierUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupplierUpsertBulk) DoNothing() *SupplierUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupplierCreateBulk.OnConflict
// documentation for more info.
func (u *SupplierUpsertBulk) Update(set func(*SupplierUpsert)) *SupplierUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupplierUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SupplierUpsertBulk) SetUpdatedAt(v time.Time) *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupplierUpsertBulk) UpdateUpdatedAt() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SupplierUpsertBulk) SetDeletedAt(v time.Time) *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SupplierUpsertBulk) UpdateDeletedAt() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SupplierUpsertBulk) ClearDeletedAt() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCode sets the "code" field.
func (u *SupplierUpsertBulk) SetCode(v string) *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *SupplierUpsertBulk) UpdateCode() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *SupplierUpsertBulk) SetName(v string) *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SupplierUpsertBulk) UpdateName() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *SupplierUpsertBulk) SetStatus(v string) *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupplierUpsertBulk) UpdateStatus() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateStatus()
	})
}

// SetNotes sets the "notes" field.
func (u *SupplierUpsertBulk) SetNotes(v string) *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SupplierUpsertBulk) UpdateNotes() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *SupplierUpsertBulk) ClearNotes() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.ClearNotes()
	})
}

// SetAllowedAccountKinds sets the "allowed_account_kinds" field.
func (u *SupplierUpsertBulk) SetAllowedAccountKinds(v []domain.SupplierAccountKind) *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.SetAllowedAccountKinds(v)
	})
}

// UpdateAllowedAccountKinds sets the "allowed_account_kinds" field to the value that was provided on create.
func (u *SupplierUpsertBulk) UpdateAllowedAccountKinds() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateAllowedAccountKinds()
	})
}

// SetReviewRequired sets the "review_required" field.
func (u *SupplierUpsertBulk) SetReviewRequired(v bool) *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.SetReviewRequired(v)
	})
}

// UpdateReviewRequired sets the "review_required" field to the value that was provided on create.
func (u *SupplierUpsertBulk) UpdateReviewRequired() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateReviewRequired()
	})
}

// SetAutoApproveGroups sets the "auto_approve_groups" field.
func (u *SupplierUpsertBulk) SetAutoApproveGroups(v map[string][]int64) *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.SetAutoApproveGroups(v)
	})
}

// UpdateAutoApproveGroups sets the "auto_approve_groups" field to the value that was provided on create.
func (u *SupplierUpsertBulk) UpdateAutoApproveGroups() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateAutoApproveGroups()
	})
}

// SetTokenSelector sets the "token_selector" field.
func (u *SupplierUpsertBulk) SetTokenSelector(v string) *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.SetTokenSelector(v)
	})
}

// UpdateTokenSelector sets the "token_selector" field to the value that was provided on create.
func (u *SupplierUpsertBulk) UpdateTokenSelector() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateTokenSelector()
	})
}

// ClearTokenSelector clears the value of the "token_selector" field.
func (u *SupplierUpsertBulk) ClearTokenSelector() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.ClearTokenSelector()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *SupplierUpsertBulk) SetTokenHash(v string) *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *SupplierUpsertBulk) UpdateTokenHash() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateTokenHash()
	})
}

// ClearTokenHash clears the value of the "token_hash" field.
func (u *SupplierUpsertBulk) ClearTokenHash() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.ClearTokenHash()
	})
}

// SetTokenPrefix sets the "token_prefix" field.
func (u *SupplierUpsertBulk) SetTokenPrefix(v string) *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.SetTokenPrefix(v)
	})
}

// UpdateTokenPrefix sets the "token_prefix" field to the value that was provided on create.
func (u *SupplierUpsertBulk) UpdateTokenPrefix() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateTokenPrefix()
	})
}

// ClearTokenPrefix clears the value of the "token_prefix" field.
func (u *SupplierUpsertBulk) ClearTokenPrefix() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.ClearTokenPrefix()
	})
}

// SetTokenCreatedAt sets the "token_created_at" field.
func (u *SupplierUpsertBulk) SetTokenCreatedAt(v time.Time) *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.SetTokenCreatedAt(v)
	})
}

// UpdateTokenCreatedAt sets the "token_created_at" field to the value that was provided on create.
func (u *SupplierUpsertBulk) UpdateTokenCreatedAt() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateTokenCreatedAt()
	})
}

// ClearTokenCreatedAt clears the value of the "token_created_at" field.
func (u *SupplierUpsertBulk) ClearTokenCreatedAt() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.ClearTokenCreatedAt()
	})
}

// SetTokenLastUsedAt sets the "token_last_used_at" field.
func (u *SupplierUpsertBulk) SetTokenLastUsedAt(v time.Time) *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.SetTokenLastUsedAt(v)
	})
}

// UpdateTokenLastUsedAt sets the "token_last_used_at" field to the value that was provided on create.
func (u *SupplierUpsertBulk) UpdateTokenLastUsedAt() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.UpdateTokenLastUsedAt()
	})
}

// ClearTokenLastUsedAt clears the value of the "token_last_used_at" field.
func (u *SupplierUpsertBulk) ClearTokenLastUsedAt() *SupplierUpsertBulk {
	return u.Update(func(s *SupplierUpsert) {
		s.ClearTokenLastUsedAt()
	})
}

// Exec executes the query.
func (u *SupplierUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SupplierCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupplierCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupplierUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
