// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/supplier"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// Supplier is the model entity for the Supplier schema.
type Supplier struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// AllowedAccountKinds holds the value of the "allowed_account_kinds" field.
	AllowedAccountKinds []domain.SupplierAccountKind `json:"allowed_account_kinds,omitempty"`
	// ReviewRequired holds the value of the "review_required" field.
	ReviewRequired bool `json:"review_required,omitempty"`
	// AutoApproveGroups holds the value of the "auto_approve_groups" field.
	AutoApproveGroups map[string][]int64 `json:"auto_approve_groups,omitempty"`
	// TokenSelector holds the value of the "token_selector" field.
	TokenSelector *string `json:"token_selector,omitempty"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash *string `json:"token_hash,omitempty"`
	// TokenPrefix holds the value of the "token_prefix" field.
	TokenPrefix *string `json:"token_prefix,omitempty"`
	// TokenCreatedAt holds the value of the "token_created_at" field.
	TokenCreatedAt *time.Time `json:"token_created_at,omitempty"`
	// TokenLastUsedAt holds the value of the "token_last_used_at" field.
	TokenLastUsedAt *time.Time `json:"token_last_used_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SupplierQuery when eager-loading is set.
	Edges        SupplierEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SupplierEdges holds the relations/edges for other nodes in the graph.
type SupplierEdges struct {
	// Members holds the value of the members edge.
	Members []*User `json:"members,omitempty"`
	// Accounts holds the value of the accounts edge.
	Accounts []*Account `json:"accounts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e SupplierEdges) MembersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading.
func (e SupplierEdges) AccountsOrErr() ([]*Account, error) {
	if e.loadedTypes[1] {
		return e.Accounts, nil
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Supplier) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case supplier.FieldAllowedAccountKinds, supplier.FieldAutoApproveGroups:
			values[i] = new([]byte)
		case supplier.FieldReviewRequired:
			values[i] = new(sql.NullBool)
		case supplier.FieldID:
			values[i] = new(sql.NullInt64)
		case supplier.FieldCode, supplier.FieldName, supplier.FieldStatus, supplier.FieldNotes, supplier.FieldTokenSelector, supplier.FieldTokenHash, supplier.FieldTokenPrefix:
			values[i] = new(sql.NullString)
		case supplier.FieldCreatedAt, supplier.FieldUpdatedAt, supplier.FieldDeletedAt, supplier.FieldTokenCreatedAt, supplier.FieldTokenLastUsedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Supplier fields.
func (_m *Supplier) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supplier.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case supplier.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case supplier.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case supplier.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case supplier.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case supplier.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case supplier.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case supplier.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case supplier.FieldAllowedAccountKinds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_account_kinds", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedAccountKinds); err != nil {
					return fmt.Errorf("unmarshal field allowed_account_kinds: %w", err)
				}
			}
		case supplier.FieldReviewRequired:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field review_required", values[i])
			} else if value.Valid {
				_m.ReviewRequired = value.Bool
			}
		case supplier.FieldAutoApproveGroups:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field auto_approve_groups", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AutoApproveGroups); err != nil {
					return fmt.Errorf("unmarshal field auto_approve_groups: %w", err)
				}
			}
		case supplier.FieldTokenSelector:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_selector", values[i])
			} else if value.Valid {
				_m.TokenSelector = new(string)
				*_m.TokenSelector = value.String
			}
		case supplier.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = new(string)
				*_m.TokenHash = value.String
			}
		case supplier.FieldTokenPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_prefix", values[i])
			} else if value.Valid {
				_m.TokenPrefix = new(string)
				*_m.TokenPrefix = value.String
			}
		case supplier.FieldTokenCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field token_created_at", values[i])
			} else if value.Valid {
				_m.TokenCreatedAt = new(time.Time)
				*_m.TokenCreatedAt = value.Time
			}
		case supplier.FieldTokenLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field token_last_used_at", values[i])
			} else if value.Valid {
				_m.TokenLastUsedAt = new(time.Time)
				*_m.TokenLastUsedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Supplier.
// This includes values selected through modifiers, order, etc.
func (_m *Supplier) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMembers queries the "members" edge of the Supplier entity.
func (_m *Supplier) QueryMembers() *UserQuery {
	return NewSupplierClient(_m.config).QueryMembers(_m)
}

// QueryAccounts queries the "accounts" edge of the Supplier entity.
func (_m *Supplier) QueryAccounts() *AccountQuery {
	return NewSupplierClient(_m.config).QueryAccounts(_m)
}

// Update returns a builder for updating this Supplier.
// Note that you need to call Supplier.Unwrap() before calling this method if this Supplier
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Supplier) Update() *SupplierUpdateOne {
	return NewSupplierClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Supplier entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Supplier) Unwrap() *Supplier {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Supplier is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Supplier) String() string {
	var builder strings.Builder
	builder.WriteString("Supplier(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("allowed_account_kinds=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedAccountKinds))
	builder.WriteString(", ")
	builder.WriteString("review_required=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReviewRequired))
	builder.WriteString(", ")
	builder.WriteString("auto_approve_groups=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoApproveGroups))
	builder.WriteString(", ")
	if v := _m.TokenSelector; v != nil {
		builder.WriteString("token_selector=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TokenHash; v != nil {
		builder.WriteString("token_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TokenPrefix; v != nil {
		builder.WriteString("token_prefix=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TokenCreatedAt; v != nil {
		builder.WriteString("token_created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TokenLastUsedAt; v != nil {
		builder.WriteString("token_last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Suppliers is a parsable slice of Supplier.
type Suppliers []*Supplier
