// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supplier"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// SupplierUpdate is the builder for updating Supplier entities.
type SupplierUpdate struct {
	config
	hooks    []Hook
	mutation *SupplierMutation
}

// Where appends a list predicates to the SupplierUpdate builder.
func (_u *SupplierUpdate) Where(ps ...predicate.Supplier) *SupplierUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupplierUpdate) SetUpdatedAt(v time.Time) *SupplierUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SupplierUpdate) SetDeletedAt(v time.Time) *SupplierUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableDeletedAt(v *time.Time) *SupplierUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SupplierUpdate) ClearDeletedAt() *SupplierUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCode sets the "code" field.
func (_u *SupplierUpdate) SetCode(v string) *SupplierUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableCode(v *string) *SupplierUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SupplierUpdate) SetName(v string) *SupplierUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableName(v *string) *SupplierUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupplierUpdate) SetStatus(v string) *SupplierUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableStatus(v *string) *SupplierUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SupplierUpdate) SetNotes(v string) *SupplierUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableNotes(v *string) *SupplierUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *SupplierUpdate) ClearNotes() *SupplierUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetAllowedAccountKinds sets the "allowed_account_kinds" field.
func (_u *SupplierUpdate) SetAllowedAccountKinds(v []domain.SupplierAccountKind) *SupplierUpdate {
	_u.mutation.SetAllowedAccountKinds(v)
	return _u
}

// AppendAllowedAccountKinds appends value to the "allowed_account_kinds" field.
func (_u *SupplierUpdate) AppendAllowedAccountKinds(v []domain.SupplierAccountKind) *SupplierUpdate {
	_u.mutation.AppendAllowedAccountKinds(v)
	return _u
}

// SetReviewRequired sets the "review_required" field.
func (_u *SupplierUpdate) SetReviewRequired(v bool) *SupplierUpdate {
	_u.mutation.SetReviewRequired(v)
	return _u
}

// SetNillableReviewRequired sets the "review_required" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableReviewRequired(v *bool) *SupplierUpdate {
	if v != nil {
		_u.SetReviewRequired(*v)
	}
	return _u
}

// SetAutoApproveGroups sets the "auto_approve_groups" field.
func (_u *SupplierUpdate) SetAutoApproveGroups(v map[string]int64) *SupplierUpdate {
	_u.mutation.SetAutoApproveGroups(v)
	return _u
}

// SetTokenSelector sets the "token_selector" field.
func (_u *SupplierUpdate) SetTokenSelector(v string) *SupplierUpdate {
	_u.mutation.SetTokenSelector(v)
	return _u
}

// SetNillableTokenSelector sets the "token_selector" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableTokenSelector(v *string) *SupplierUpdate {
	if v != nil {
		_u.SetTokenSelector(*v)
	}
	return _u
}

// ClearTokenSelector clears the value of the "token_selector" field.
func (_u *SupplierUpdate) ClearTokenSelector() *SupplierUpdate {
	_u.mutation.ClearTokenSelector()
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *SupplierUpdate) SetTokenHash(v string) *SupplierUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableTokenHash(v *string) *SupplierUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// ClearTokenHash clears the value of the "token_hash" field.
func (_u *SupplierUpdate) ClearTokenHash() *SupplierUpdate {
	_u.mutation.ClearTokenHash()
	return _u
}

// SetTokenPrefix sets the "token_prefix" field.
func (_u *SupplierUpdate) SetTokenPrefix(v string) *SupplierUpdate {
	_u.mutation.SetTokenPrefix(v)
	return _u
}

// SetNillableTokenPrefix sets the "token_prefix" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableTokenPrefix(v *string) *SupplierUpdate {
	if v != nil {
		_u.SetTokenPrefix(*v)
	}
	return _u
}

// ClearTokenPrefix clears the value of the "token_prefix" field.
func (_u *SupplierUpdate) ClearTokenPrefix() *SupplierUpdate {
	_u.mutation.ClearTokenPrefix()
	return _u
}

// SetTokenCreatedAt sets the "token_created_at" field.
func (_u *SupplierUpdate) SetTokenCreatedAt(v time.Time) *SupplierUpdate {
	_u.mutation.SetTokenCreatedAt(v)
	return _u
}

// SetNillableTokenCreatedAt sets the "token_created_at" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableTokenCreatedAt(v *time.Time) *SupplierUpdate {
	if v != nil {
		_u.SetTokenCreatedAt(*v)
	}
	return _u
}

// ClearTokenCreatedAt clears the value of the "token_created_at" field.
func (_u *SupplierUpdate) ClearTokenCreatedAt() *SupplierUpdate {
	_u.mutation.ClearTokenCreatedAt()
	return _u
}

// SetTokenLastUsedAt sets the "token_last_used_at" field.
func (_u *SupplierUpdate) SetTokenLastUsedAt(v time.Time) *SupplierUpdate {
	_u.mutation.SetTokenLastUsedAt(v)
	return _u
}

// SetNillableTokenLastUsedAt sets the "token_last_used_at" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableTokenLastUsedAt(v *time.Time) *SupplierUpdate {
	if v != nil {
		_u.SetTokenLastUsedAt(*v)
	}
	return _u
}

// ClearTokenLastUsedAt clears the value of the "token_last_used_at" field.
func (_u *SupplierUpdate) ClearTokenLastUsedAt() *SupplierUpdate {
	_u.mutation.ClearTokenLastUsedAt()
	return _u
}

// AddMemberIDs adds the "members" edge to the User entity by IDs.
func (_u *SupplierUpdate) AddMemberIDs(ids ...int64) *SupplierUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the User entity.
func (_u *SupplierUpdate) AddMembers(v ...*User) *SupplierUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *SupplierUpdate) AddAccountIDs(ids ...int64) *SupplierUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *SupplierUpdate) AddAccounts(v ...*Account) *SupplierUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the SupplierMutation object of the builder.
func (_u *SupplierUpdate) Mutation() *SupplierMutation {
	return _u.mutation
}

// ClearMembers clears all "members" edges to the User entity.
func (_u *SupplierUpdate) ClearMembers() *SupplierUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to User entities by IDs.
func (_u *SupplierUpdate) RemoveMemberIDs(ids ...int64) *SupplierUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to User entities.
func (_u *SupplierUpdate) RemoveMembers(v ...*User) *SupplierUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *SupplierUpdate) ClearAccounts() *SupplierUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *SupplierUpdate) RemoveAccountIDs(ids ...int64) *SupplierUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *SupplierUpdate) RemoveAccounts(v ...*Account) *SupplierUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupplierUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupplierUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupplierUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupplierUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupplierUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if supplier.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized supplier.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := supplier.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupplierUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := supplier.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Supplier.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := supplier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Supplier.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supplier.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Supplier.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenSelector(); ok {
		if err := supplier.TokenSelectorValidator(v); err != nil {
			return &ValidationError{Name: "token_selector", err: fmt.Errorf(`ent: validator failed for field "Supplier.token_selector": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := supplier.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "Supplier.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenPrefix(); ok {
		if err := supplier.TokenPrefixValidator(v); err != nil {
			return &ValidationError{Name: "token_prefix", err: fmt.Errorf(`ent: validator failed for field "Supplier.token_prefix": %w`, err)}
		}
	}
	return nil
}

func (_u *SupplierUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supplier.Table, supplier.Columns, sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supplier.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(supplier.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(supplier.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(supplier.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(supplier.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supplier.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(supplier.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(supplier.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.AllowedAccountKinds(); ok {
		_spec.SetField(supplier.FieldAllowedAccountKinds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedAccountKinds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, supplier.FieldAllowedAccountKinds, value)
		})
	}
	if value, ok := _u.mutation.ReviewRequired(); ok {
		_spec.SetField(supplier.FieldReviewRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AutoApproveGroups(); ok {
		_spec.SetField(supplier.FieldAutoApproveGroups, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.TokenSelector(); ok {
		_spec.SetField(supplier.FieldTokenSelector, field.TypeString, value)
	}
	if _u.mutation.TokenSelectorCleared() {
		_spec.ClearField(supplier.FieldTokenSelector, field.TypeString)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(supplier.FieldTokenHash, field.TypeString, value)
	}
	if _u.mutation.TokenHashCleared() {
		_spec.ClearField(supplier.FieldTokenHash, field.TypeString)
	}
	if value, ok := _u.mutation.TokenPrefix(); ok {
		_spec.SetField(supplier.FieldTokenPrefix, field.TypeString, value)
	}
	if _u.mutation.TokenPrefixCleared() {
		_spec.ClearField(supplier.FieldTokenPrefix, field.TypeString)
	}
	if value, ok := _u.mutation.TokenCreatedAt(); ok {
		_spec.SetField(supplier.FieldTokenCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.TokenCreatedAtCleared() {
		_spec.ClearField(supplier.FieldTokenCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TokenLastUsedAt(); ok {
		_spec.SetField(supplier.FieldTokenLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.TokenLastUsedAtCleared() {
		_spec.ClearField(supplier.FieldTokenLastUsedAt, field.TypeTime)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.MembersTable,
			Columns: []string{supplier.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.MembersTable,
			Columns: []string{supplier.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.MembersTable,
			Columns: []string{supplier.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.AccountsTable,
			Columns: []string{supplier.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.AccountsTable,
			Columns: []string{supplier.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.AccountsTable,
			Columns: []string{supplier.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supplier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupplierUpdateOne is the builder for updating a single Supplier entity.
type SupplierUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupplierMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupplierUpdateOne) SetUpdatedAt(v time.Time) *SupplierUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SupplierUpdateOne) SetDeletedAt(v time.Time) *SupplierUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableDeletedAt(v *time.Time) *SupplierUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SupplierUpdateOne) ClearDeletedAt() *SupplierUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCode sets the "code" field.
func (_u *SupplierUpdateOne) SetCode(v string) *SupplierUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableCode(v *string) *SupplierUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SupplierUpdateOne) SetName(v string) *SupplierUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableName(v *string) *SupplierUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupplierUpdateOne) SetStatus(v string) *SupplierUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableStatus(v *string) *SupplierUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SupplierUpdateOne) SetNotes(v string) *SupplierUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableNotes(v *string) *SupplierUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *SupplierUpdateOne) ClearNotes() *SupplierUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetAllowedAccountKinds sets the "allowed_account_kinds" field.
func (_u *SupplierUpdateOne) SetAllowedAccountKinds(v []domain.SupplierAccountKind) *SupplierUpdateOne {
	_u.mutation.SetAllowedAccountKinds(v)
	return _u
}

// AppendAllowedAccountKinds appends value to the "allowed_account_kinds" field.
func (_u *SupplierUpdateOne) AppendAllowedAccountKinds(v []domain.SupplierAccountKind) *SupplierUpdateOne {
	_u.mutation.AppendAllowedAccountKinds(v)
	return _u
}

// SetReviewRequired sets the "review_required" field.
func (_u *SupplierUpdateOne) SetReviewRequired(v bool) *SupplierUpdateOne {
	_u.mutation.SetReviewRequired(v)
	return _u
}

// SetNillableReviewRequired sets the "review_required" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableReviewRequired(v *bool) *SupplierUpdateOne {
	if v != nil {
		_u.SetReviewRequired(*v)
	}
	return _u
}

// SetAutoApproveGroups sets the "auto_approve_groups" field.
func (_u *SupplierUpdateOne) SetAutoApproveGroups(v map[string]int64) *SupplierUpdateOne {
	_u.mutation.SetAutoApproveGroups(v)
	return _u
}

// SetTokenSelector sets the "token_selector" field.
func (_u *SupplierUpdateOne) SetTokenSelector(v string) *SupplierUpdateOne {
	_u.mutation.SetTokenSelector(v)
	return _u
}

// SetNillableTokenSelector sets the "token_selector" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableTokenSelector(v *string) *SupplierUpdateOne {
	if v != nil {
		_u.SetTokenSelector(*v)
	}
	return _u
}

// ClearTokenSelector clears the value of the "token_selector" field.
func (_u *SupplierUpdateOne) ClearTokenSelector() *SupplierUpdateOne {
	_u.mutation.ClearTokenSelector()
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *SupplierUpdateOne) SetTokenHash(v string) *SupplierUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableTokenHash(v *string) *SupplierUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// ClearTokenHash clears the value of the "token_hash" field.
func (_u *SupplierUpdateOne) ClearTokenHash() *SupplierUpdateOne {
	_u.mutation.ClearTokenHash()
	return _u
}

// SetTokenPrefix sets the "token_prefix" field.
func (_u *SupplierUpdateOne) SetTokenPrefix(v string) *SupplierUpdateOne {
	_u.mutation.SetTokenPrefix(v)
	return _u
}

// SetNillableTokenPrefix sets the "token_prefix" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableTokenPrefix(v *string) *SupplierUpdateOne {
	if v != nil {
		_u.SetTokenPrefix(*v)
	}
	return _u
}

// ClearTokenPrefix clears the value of the "token_prefix" field.
func (_u *SupplierUpdateOne) ClearTokenPrefix() *SupplierUpdateOne {
	_u.mutation.ClearTokenPrefix()
	return _u
}

// SetTokenCreatedAt sets the "token_created_at" field.
func (_u *SupplierUpdateOne) SetTokenCreatedAt(v time.Time) *SupplierUpdateOne {
	_u.mutation.SetTokenCreatedAt(v)
	return _u
}

// SetNillableTokenCreatedAt sets the "token_created_at" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableTokenCreatedAt(v *time.Time) *SupplierUpdateOne {
	if v != nil {
		_u.SetTokenCreatedAt(*v)
	}
	return _u
}

// ClearTokenCreatedAt clears the value of the "token_created_at" field.
func (_u *SupplierUpdateOne) ClearTokenCreatedAt() *SupplierUpdateOne {
	_u.mutation.ClearTokenCreatedAt()
	return _u
}

// SetTokenLastUsedAt sets the "token_last_used_at" field.
func (_u *SupplierUpdateOne) SetTokenLastUsedAt(v time.Time) *SupplierUpdateOne {
	_u.mutation.SetTokenLastUsedAt(v)
	return _u
}

// SetNillableTokenLastUsedAt sets the "token_last_used_at" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableTokenLastUsedAt(v *time.Time) *SupplierUpdateOne {
	if v != nil {
		_u.SetTokenLastUsedAt(*v)
	}
	return _u
}

// ClearTokenLastUsedAt clears the value of the "token_last_used_at" field.
func (_u *SupplierUpdateOne) ClearTokenLastUsedAt() *SupplierUpdateOne {
	_u.mutation.ClearTokenLastUsedAt()
	return _u
}

// AddMemberIDs adds the "members" edge to the User entity by IDs.
func (_u *SupplierUpdateOne) AddMemberIDs(ids ...int64) *SupplierUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the User entity.
func (_u *SupplierUpdateOne) AddMembers(v ...*User) *SupplierUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *SupplierUpdateOne) AddAccountIDs(ids ...int64) *SupplierUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *SupplierUpdateOne) AddAccounts(v ...*Account) *SupplierUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the SupplierMutation object of the builder.
func (_u *SupplierUpdateOne) Mutation() *SupplierMutation {
	return _u.mutation
}

// ClearMembers clears all "members" edges to the User entity.
func (_u *SupplierUpdateOne) ClearMembers() *SupplierUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to User entities by IDs.
func (_u *SupplierUpdateOne) RemoveMemberIDs(ids ...int64) *SupplierUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to User entities.
func (_u *SupplierUpdateOne) RemoveMembers(v ...*User) *SupplierUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *SupplierUpdateOne) ClearAccounts() *SupplierUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *SupplierUpdateOne) RemoveAccountIDs(ids ...int64) *SupplierUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *SupplierUpdateOne) RemoveAccounts(v ...*Account) *SupplierUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Where appends a list predicates to the SupplierUpdate builder.
func (_u *SupplierUpdateOne) Where(ps ...predicate.Supplier) *SupplierUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupplierUpdateOne) Select(field string, fields ...string) *SupplierUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Supplier entity.
func (_u *SupplierUpdateOne) Save(ctx context.Context) (*Supplier, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupplierUpdateOne) SaveX(ctx context.Context) *Supplier {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupplierUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupplierUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupplierUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if supplier.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized supplier.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := supplier.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupplierUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := supplier.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Supplier.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := supplier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Supplier.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supplier.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Supplier.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenSelector(); ok {
		if err := supplier.TokenSelectorValidator(v); err != nil {
			return &ValidationError{Name: "token_selector", err: fmt.Errorf(`ent: validator failed for field "Supplier.token_selector": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := supplier.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "Supplier.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenPrefix(); ok {
		if err := supplier.TokenPrefixValidator(v); err != nil {
			return &ValidationError{Name: "token_prefix", err: fmt.Errorf(`ent: validator failed for field "Supplier.token_prefix": %w`, err)}
		}
	}
	return nil
}

func (_u *SupplierUpdateOne) sqlSave(ctx context.Context) (_node *Supplier, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supplier.Table, supplier.Columns, sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Supplier.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supplier.FieldID)
		for _, f := range fields {
			if !supplier.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supplier.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supplier.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(supplier.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(supplier.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(supplier.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(supplier.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supplier.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(supplier.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(supplier.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.AllowedAccountKinds(); ok {
		_spec.SetField(supplier.FieldAllowedAccountKinds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedAccountKinds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, supplier.FieldAllowedAccountKinds, value)
		})
	}
	if value, ok := _u.mutation.ReviewRequired(); ok {
		_spec.SetField(supplier.FieldReviewRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AutoApproveGroups(); ok {
		_spec.SetField(supplier.FieldAutoApproveGroups, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.TokenSelector(); ok {
		_spec.SetField(supplier.FieldTokenSelector, field.TypeString, value)
	}
	if _u.mutation.TokenSelectorCleared() {
		_spec.ClearField(supplier.FieldTokenSelector, field.TypeString)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(supplier.FieldTokenHash, field.TypeString, value)
	}
	if _u.mutation.TokenHashCleared() {
		_spec.ClearField(supplier.FieldTokenHash, field.TypeString)
	}
	if value, ok := _u.mutation.TokenPrefix(); ok {
		_spec.SetField(supplier.FieldTokenPrefix, field.TypeString, value)
	}
	if _u.mutation.TokenPrefixCleared() {
		_spec.ClearField(supplier.FieldTokenPrefix, field.TypeString)
	}
	if value, ok := _u.mutation.TokenCreatedAt(); ok {
		_spec.SetField(supplier.FieldTokenCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.TokenCreatedAtCleared() {
		_spec.ClearField(supplier.FieldTokenCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TokenLastUsedAt(); ok {
		_spec.SetField(supplier.FieldTokenLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.TokenLastUsedAtCleared() {
		_spec.ClearField(supplier.FieldTokenLastUsedAt, field.TypeTime)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.MembersTable,
			Columns: []string{supplier.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.MembersTable,
			Columns: []string{supplier.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.MembersTable,
			Columns: []string{supplier.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.AccountsTable,
			Columns: []string{supplier.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.AccountsTable,
			Columns: []string{supplier.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.AccountsTable,
			Columns: []string{supplier.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Supplier{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supplier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
