// Code generated by ent, DO NOT EDIT.

package supplier

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

const (
	// Label holds the string label denoting the supplier type in the database.
	Label = "supplier"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldAllowedAccountKinds holds the string denoting the allowed_account_kinds field in the database.
	FieldAllowedAccountKinds = "allowed_account_kinds"
	// FieldReviewRequired holds the string denoting the review_required field in the database.
	FieldReviewRequired = "review_required"
	// FieldAutoApproveGroups holds the string denoting the auto_approve_groups field in the database.
	FieldAutoApproveGroups = "auto_approve_groups"
	// FieldTokenSelector holds the string denoting the token_selector field in the database.
	FieldTokenSelector = "token_selector"
	// FieldTokenHash holds the string denoting the token_hash field in the database.
	FieldTokenHash = "token_hash"
	// FieldTokenPrefix holds the string denoting the token_prefix field in the database.
	FieldTokenPrefix = "token_prefix"
	// FieldTokenCreatedAt holds the string denoting the token_created_at field in the database.
	FieldTokenCreatedAt = "token_created_at"
	// FieldTokenLastUsedAt holds the string denoting the token_last_used_at field in the database.
	FieldTokenLastUsedAt = "token_last_used_at"
	// EdgeMembers holds the string denoting the members edge name in mutations.
	EdgeMembers = "members"
	// EdgeAccounts holds the string denoting the accounts edge name in mutations.
	EdgeAccounts = "accounts"
	// Table holds the table name of the supplier in the database.
	Table = "suppliers"
	// MembersTable is the table that holds the members relation/edge.
	MembersTable = "users"
	// MembersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	MembersInverseTable = "users"
	// MembersColumn is the table column denoting the members relation/edge.
	MembersColumn = "supplier_id"
	// AccountsTable is the table that holds the accounts relation/edge.
	AccountsTable = "accounts"
	// AccountsInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountsInverseTable = "accounts"
	// AccountsColumn is the table column denoting the accounts relation/edge.
	AccountsColumn = "supplier_id"
)

// Columns holds all SQL columns for supplier fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCode,
	FieldName,
	FieldStatus,
	FieldNotes,
	FieldAllowedAccountKinds,
	FieldReviewRequired,
	FieldAutoApproveGroups,
	FieldTokenSelector,
	FieldTokenHash,
	FieldTokenPrefix,
	FieldTokenCreatedAt,
	FieldTokenLastUsedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultAllowedAccountKinds holds the default value on creation for the "allowed_account_kinds" field.
	DefaultAllowedAccountKinds func() []domain.SupplierAccountKind
	// DefaultReviewRequired holds the default value on creation for the "review_required" field.
	DefaultReviewRequired bool
	// DefaultAutoApproveGroups holds the default value on creation for the "auto_approve_groups" field.
	DefaultAutoApproveGroups func() map[string][]int64
	// TokenSelectorValidator is a validator for the "token_selector" field. It is called by the builders before save.
	TokenSelectorValidator func(string) error
	// TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	TokenHashValidator func(string) error
	// TokenPrefixValidator is a validator for the "token_prefix" field. It is called by the builders before save.
	TokenPrefixValidator func(string) error
)

// OrderOption defines the ordering options for the Supplier queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByReviewRequired orders the results by the review_required field.
func ByReviewRequired(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewRequired, opts...).ToFunc()
}

// ByTokenSelector orders the results by the token_selector field.
func ByTokenSelector(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenSelector, opts...).ToFunc()
}

// ByTokenHash orders the results by the token_hash field.
func ByTokenHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenHash, opts...).ToFunc()
}

// ByTokenPrefix orders the results by the token_prefix field.
func ByTokenPrefix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenPrefix, opts...).ToFunc()
}

// ByTokenCreatedAt orders the results by the token_created_at field.
func ByTokenCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenCreatedAt, opts...).ToFunc()
}

// ByTokenLastUsedAt orders the results by the token_last_used_at field.
func ByTokenLastUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenLastUsedAt, opts...).ToFunc()
}

// ByMembersCount orders the results by members count.
func ByMembersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMembersStep(), opts...)
	}
}

// ByMembers orders the results by members terms.
func ByMembers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMembersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAccountsCount orders the results by accounts count.
func ByAccountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccountsStep(), opts...)
	}
}

// ByAccounts orders the results by accounts terms.
func ByAccounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMembersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MembersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, MembersTable, MembersColumn),
	)
}
func newAccountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, AccountsTable, AccountsColumn),
	)
}
