// Code generated by ent, DO NOT EDIT.

package supplier

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldDeletedAt, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldName, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldStatus, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldNotes, v))
}

// TokenSelector applies equality check predicate on the "token_selector" field. It's identical to TokenSelectorEQ.
func TokenSelector(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldTokenSelector, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldTokenHash, v))
}

// TokenPrefix applies equality check predicate on the "token_prefix" field. It's identical to TokenPrefixEQ.
func TokenPrefix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldTokenPrefix, v))
}

// TokenCreatedAt applies equality check predicate on the "token_created_at" field. It's identical to TokenCreatedAtEQ.
func TokenCreatedAt(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldTokenCreatedAt, v))
}

// TokenLastUsedAt applies equality check predicate on the "token_last_used_at" field. It's identical to TokenLastUsedAtEQ.
func TokenLastUsedAt(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldTokenLastUsedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldNotNull(FieldDeletedAt))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContainsFold(FieldCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContainsFold(FieldName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContainsFold(FieldStatus, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContainsFold(FieldNotes, v))
}

// TokenSelectorEQ applies the EQ predicate on the "token_selector" field.
func TokenSelectorEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldTokenSelector, v))
}

// TokenSelectorNEQ applies the NEQ predicate on the "token_selector" field.
func TokenSelectorNEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldTokenSelector, v))
}

// TokenSelectorIn applies the In predicate on the "token_selector" field.
func TokenSelectorIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldTokenSelector, vs...))
}

// TokenSelectorNotIn applies the NotIn predicate on the "token_selector" field.
func TokenSelectorNotIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldTokenSelector, vs...))
}

// TokenSelectorGT applies the GT predicate on the "token_selector" field.
func TokenSelectorGT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldTokenSelector, v))
}

// TokenSelectorGTE applies the GTE predicate on the "token_selector" field.
func TokenSelectorGTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldTokenSelector, v))
}

// TokenSelectorLT applies the LT predicate on the "token_selector" field.
func TokenSelectorLT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldTokenSelector, v))
}

// TokenSelectorLTE applies the LTE predicate on the "token_selector" field.
func TokenSelectorLTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldTokenSelector, v))
}

// TokenSelectorContains applies the Contains predicate on the "token_selector" field.
func TokenSelectorContains(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContains(FieldTokenSelector, v))
}

// TokenSelectorHasPrefix applies the HasPrefix predicate on the "token_selector" field.
func TokenSelectorHasPrefix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasPrefix(FieldTokenSelector, v))
}

// TokenSelectorHasSuffix applies the HasSuffix predicate on the "token_selector" field.
func TokenSelectorHasSuffix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasSuffix(FieldTokenSelector, v))
}

// TokenSelectorIsNil applies the IsNil predicate on the "token_selector" field.
func TokenSelectorIsNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldIsNull(FieldTokenSelector))
}

// TokenSelectorNotNil applies the NotNil predicate on the "token_selector" field.
func TokenSelectorNotNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldNotNull(FieldTokenSelector))
}

// TokenSelectorEqualFold applies the EqualFold predicate on the "token_selector" field.
func TokenSelectorEqualFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEqualFold(FieldTokenSelector, v))
}

// TokenSelectorContainsFold applies the ContainsFold predicate on the "token_selector" field.
func TokenSelectorContainsFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContainsFold(FieldTokenSelector, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashIsNil applies the IsNil predicate on the "token_hash" field.
func TokenHashIsNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldIsNull(FieldTokenHash))
}

// TokenHashNotNil applies the NotNil predicate on the "token_hash" field.
func TokenHashNotNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldNotNull(FieldTokenHash))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContainsFold(FieldTokenHash, v))
}

// TokenPrefixEQ applies the EQ predicate on the "token_prefix" field.
func TokenPrefixEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldTokenPrefix, v))
}

// TokenPrefixNEQ applies the NEQ predicate on the "token_prefix" field.
func TokenPrefixNEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldTokenPrefix, v))
}

// TokenPrefixIn applies the In predicate on the "token_prefix" field.
func TokenPrefixIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldTokenPrefix, vs...))
}

// TokenPrefixNotIn applies the NotIn predicate on the "token_prefix" field.
func TokenPrefixNotIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldTokenPrefix, vs...))
}

// TokenPrefixGT applies the GT predicate on the "token_prefix" field.
func TokenPrefixGT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldTokenPrefix, v))
}

// TokenPrefixGTE applies the GTE predicate on the "token_prefix" field.
func TokenPrefixGTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldTokenPrefix, v))
}

// TokenPrefixLT applies the LT predicate on the "token_prefix" field.
func TokenPrefixLT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldTokenPrefix, v))
}

// TokenPrefixLTE applies the LTE predicate on the "token_prefix" field.
func TokenPrefixLTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldTokenPrefix, v))
}

// TokenPrefixContains applies the Contains predicate on the "token_prefix" field.
func TokenPrefixContains(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContains(FieldTokenPrefix, v))
}

// TokenPrefixHasPrefix applies the HasPrefix predicate on the "token_prefix" field.
func TokenPrefixHasPrefix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasPrefix(FieldTokenPrefix, v))
}

// TokenPrefixHasSuffix applies the HasSuffix predicate on the "token_prefix" field.
func TokenPrefixHasSuffix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasSuffix(FieldTokenPrefix, v))
}

// TokenPrefixIsNil applies the IsNil predicate on the "token_prefix" field.
func TokenPrefixIsNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldIsNull(FieldTokenPrefix))
}

// TokenPrefixNotNil applies the NotNil predicate on the "token_prefix" field.
func TokenPrefixNotNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldNotNull(FieldTokenPrefix))
}

// TokenPrefixEqualFold applies the EqualFold predicate on the "token_prefix" field.
func TokenPrefixEqualFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEqualFold(FieldTokenPrefix, v))
}

// TokenPrefixContainsFold applies the ContainsFold predicate on the "token_prefix" field.
func TokenPrefixContainsFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContainsFold(FieldTokenPrefix, v))
}

// TokenCreatedAtEQ applies the EQ predicate on the "token_created_at" field.
func TokenCreatedAtEQ(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldTokenCreatedAt, v))
}

// TokenCreatedAtNEQ applies the NEQ predicate on the "token_created_at" field.
func TokenCreatedAtNEQ(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldTokenCreatedAt, v))
}

// TokenCreatedAtIn applies the In predicate on the "token_created_at" field.
func TokenCreatedAtIn(vs ...time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldTokenCreatedAt, vs...))
}

// TokenCreatedAtNotIn applies the NotIn predicate on the "token_created_at" field.
func TokenCreatedAtNotIn(vs ...time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldTokenCreatedAt, vs...))
}

// TokenCreatedAtGT applies the GT predicate on the "token_created_at" field.
func TokenCreatedAtGT(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldTokenCreatedAt, v))
}

// TokenCreatedAtGTE applies the GTE predicate on the "token_created_at" field.
func TokenCreatedAtGTE(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldTokenCreatedAt, v))
}

// TokenCreatedAtLT applies the LT predicate on the "token_created_at" field.
func TokenCreatedAtLT(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldTokenCreatedAt, v))
}

// TokenCreatedAtLTE applies the LTE predicate on the "token_created_at" field.
func TokenCreatedAtLTE(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldTokenCreatedAt, v))
}

// TokenCreatedAtIsNil applies the IsNil predicate on the "token_created_at" field.
func TokenCreatedAtIsNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldIsNull(FieldTokenCreatedAt))
}

// TokenCreatedAtNotNil applies the NotNil predicate on the "token_created_at" field.
func TokenCreatedAtNotNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldNotNull(FieldTokenCreatedAt))
}

// TokenLastUsedAtEQ applies the EQ predicate on the "token_last_used_at" field.
func TokenLastUsedAtEQ(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldTokenLastUsedAt, v))
}

// TokenLastUsedAtNEQ applies the NEQ predicate on the "token_last_used_at" field.
func TokenLastUsedAtNEQ(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldTokenLastUsedAt, v))
}

// TokenLastUsedAtIn applies the In predicate on the "token_last_used_at" field.
func TokenLastUsedAtIn(vs ...time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldTokenLastUsedAt, vs...))
}

// TokenLastUsedAtNotIn applies the NotIn predicate on the "token_last_used_at" field.
func TokenLastUsedAtNotIn(vs ...time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldTokenLastUsedAt, vs...))
}

// TokenLastUsedAtGT applies the GT predicate on the "token_last_used_at" field.
func TokenLastUsedAtGT(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldTokenLastUsedAt, v))
}

// TokenLastUsedAtGTE applies the GTE predicate on the "token_last_used_at" field.
func TokenLastUsedAtGTE(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldTokenLastUsedAt, v))
}

// TokenLastUsedAtLT applies the LT predicate on the "token_last_used_at" field.
func TokenLastUsedAtLT(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldTokenLastUsedAt, v))
}

// TokenLastUsedAtLTE applies the LTE predicate on the "token_last_used_at" field.
func TokenLastUsedAtLTE(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldTokenLastUsedAt, v))
}

// TokenLastUsedAtIsNil applies the IsNil predicate on the "token_last_used_at" field.
func TokenLastUsedAtIsNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldIsNull(FieldTokenLastUsedAt))
}

// TokenLastUsedAtNotNil applies the NotNil predicate on the "token_last_used_at" field.
func TokenLastUsedAtNotNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldNotNull(FieldTokenLastUsedAt))
}

// HasMembers applies the HasEdge predicate on the "members" edge.
func HasMembers() predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, MembersTable, MembersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMembersWith applies the HasEdge predicate on the "members" edge with a given conditions (other predicates).
func HasMembersWith(preds ...predicate.User) predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := newMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Supplier) predicate.Supplier {
	return predicate.Supplier(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Supplier) predicate.Supplier {
	return predicate.Supplier(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Supplier) predicate.Supplier {
	return predicate.Supplier(sql.NotPredicates(p))
}
